analyzer:
  exclude:
    - /**/*.g.dart
    - bricks/**
  errors:
    # put 'error' instead of 'warning' if you want compiler to fail if you made a mistake
    avoid_print: warning
    unawaited_futures: warning
    discarded_futures: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    use_build_context_synchronously: warning
    use_string_buffers: warning
    empty_catches: warning
    avoid_unnecessary_containers: warning

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - unawaited_futures
    - discarded_futures
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - provide_deprecation_message
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_breaks
    - unnecessary_getters_setters
    - unnecessary_null_in_if_null_operators
    - unnecessary_new
    - use_build_context_synchronously
    - package_names
    - close_sinks
    - avoid_print
    - avoid_empty_else
    - use_string_buffers
    - unnecessary_parenthesis
    - no_self_assignments
    - prefer_void_to_null
    - unnecessary_await_in_return
    - avoid_void_async
    - await_only_futures
    - cast_nullable_to_non_nullable
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_conditional_assignment
    - avoid_unnecessary_containers
    - always_put_control_body_on_new_line
    - avoid_relative_lib_imports