name: commerce_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  commerce_dart_sdk: 
    git:
      url: git@github.com:InsiteSoftware/commerce-dart-sdk.git
      ref: develop
  shared_preferences: ^2.2.0
  get_it: ^7.6.4

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
