name: commerce_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  go_router: ^13.2.0
  google_fonts: 6.1.0
  url_launcher: ^6.1.12
  map_launcher: ^3.2.0
  optimizely_commerce_api:
    git:
      url: git@github.com:InsiteSoftware/commerce-dart-sdk.git
      ref: develop
  shared_preferences: ^2.2.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  flutter_widget_from_html: ^0.14.11
  loading_animation_widget:


dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.1
  mocktail: ^1.0.2
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/bar_icons/
