name: commerce_dart_sdk
description: SDK for Optimizely Configured Commerce
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod: ^2.3.10

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
