name: commerce_dart_sdk
description: SDK for Optimizely Configured Commerce
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1
  dio_intercept_to_curl: ^0.1.0
  flutter:
      sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
      sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
