name: Customer Build
on:
  workflow_dispatch:
    inputs:
      release_env:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - beta
      test_group:
        description: 'Tester group'
        required: true
        default: 'none'
        type: choice
        options:
          - all
          - none
          - qa
          - customers
          - dummy

jobs:
  ios:
    runs-on: macos-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: |
          ls -l

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter --version

      - run: flutter doctor -v

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Fastlane
        run: |
          RELEASE_ENV='${{ github.event.inputs.release_env }}'
          TEST_GROUP='${{ github.event.inputs.test_group }}'

          echo "Using RELEASE_ENV: $RELEASE_ENV and TEST_GROUP: $TEST_GROUP"
          
          fastlane ios $RELEASE_ENV release:$TEST_GROUP
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  android:    
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: |
          ls -l

      - name: Set up Java
        uses: actions/setup-java@v2
        with: 
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter --version

      - run: flutter doctor -v

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Fastlane
        run: |
          RELEASE_ENV='${{ github.event.inputs.release_env }}'
          TEST_GROUP='${{ github.event.inputs.test_group }}'

          echo "Using RELEASE_ENV: $RELEASE_ENV and TEST_GROUP: $TEST_GROUP"
          
          fastlane android $RELEASE_ENV release:$TEST_GROUP
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}