name: Dev Build
on:
  pull_request:
    branches:
      - main
      - develop
      - epic/*
      - story/*
  workflow_dispatch:
    inputs:
      release:
        description: 'Release for'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - customers
          - test

jobs:
  ios:
    runs-on: macos-latest
    steps: 
      - name: Preparing build
        run: echo "Preparing this build for ${{ github.event.inputs.release }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: |
          ls -l

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter --version

      - run: flutter doctor -v

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Cloning build scripts
        uses: actions/checkout@master
        with:
          repository: InsiteSoftware/commerce-mobile-build-scripts
          ref: refs/heads/flutter
          token: ${{ secrets.my_pat }}
          path: build-scripts
      - name: List out everything
        run: |
          mv build-scripts/* ./
          ls -l
          ls -l fastlane
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Fastlane
        run: |
          fastlane ios qa release:${{ inputs.release }} 
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
  android:
    runs-on: macos-latest
    steps:
      - name: Preparing build
        run: echo "Preparing this build for ${{ github.event.inputs.release }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: |
          ls -l

      - name: Set up Java
        uses: actions/setup-java@v2
        with: 
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter --version

      - run: flutter doctor -v

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Cloning build scripts
        uses: actions/checkout@master
        with:
          repository: InsiteSoftware/commerce-mobile-build-scripts
          ref: refs/heads/flutter
          token: ${{ secrets.my_pat }}
          path: build-scripts
      - name: List out everything
        run: |
          mv build-scripts/* ./
          ls -l
          ls -l fastlane
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Fastlane
        run: |
          fastlane android qa release:${{ inputs.release }} 
          ls -l
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}