name: license_check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'pubspec.yaml'
      - '.github/workflows/license_check.yaml'
  push:
    branches: 
      - main
      - develop
    paths:
      - 'pubspec.yaml'
      - '.github/workflows/license_check.yaml'

jobs:
  license_check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/license_check.yml@v1
    with:
      allowed: 'MIT,Apache-2.0,Apache 2.0,BSD-3-Clause,BSD-2-Clause,BSD Zero Clause,Apache-2.0 AND BSD-2-Clause,(Apache-2.0 OR BSD-3-Clause),ISC,MS-PL,MS-EULA,MS-EULA-Non-Redistributable,Commercial,(OFL-1.1 AND MIT),BSD,0BSD,Unlicense,Custom: https://www.froala.com/wysiwyg-editor'
